name: main

on: [push]

jobs:
  test-lambda-functions:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        cd get_function
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cd ../put_function
        pip install -r requirements.txt
        cd ..

    - name: Run tests for get_function
      run:
        pytest get_function

    - name: Run tests for put_function
      run: 
        pytest put_function

  deploy-infra:
    needs: test-lambda-functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
